/* simple-vala.c generated by valac 0.24.0, the Vala compiler
 * generated from simple-vala.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gtkspell/gtkspell.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_WINDOW (window_get_type ())
#define WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_WINDOW, Window))
#define WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_WINDOW, WindowClass))
#define IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_WINDOW))
#define IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_WINDOW))
#define WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_WINDOW, WindowClass))

typedef struct _Window Window;
typedef struct _WindowClass WindowClass;
typedef struct _WindowPrivate WindowPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _Window {
	GtkWindow parent_instance;
	WindowPrivate * priv;
};

struct _WindowClass {
	GtkWindowClass parent_class;
};

struct _WindowPrivate {
	GtkLabel* label;
};


static gpointer window_parent_class = NULL;

GType window_get_type (void) G_GNUC_CONST;
#define WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_WINDOW, WindowPrivate))
enum  {
	WINDOW_DUMMY_PROPERTY
};
Window* window_new (void);
Window* window_construct (GType object_type);
static GObject * window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void window_finalize (GObject* obj);
gint _vala_main (gchar** args, int args_length1);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);


Window* window_construct (GType object_type) {
	Window * self = NULL;
	self = (Window*) g_object_new (object_type, NULL);
	return self;
}


Window* window_new (void) {
	return window_construct (TYPE_WINDOW);
}


static GObject * window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	Window * self;
	GtkBox* box = NULL;
	GtkBox* _tmp0_ = NULL;
	GtkBox* _tmp1_ = NULL;
	GtkBox* _tmp2_ = NULL;
	GtkLabel* _tmp3_ = NULL;
	GtkScrolledWindow* scroll = NULL;
	GtkScrolledWindow* _tmp4_ = NULL;
	GtkBox* _tmp5_ = NULL;
	GtkScrolledWindow* _tmp6_ = NULL;
	GtkScrolledWindow* _tmp7_ = NULL;
	GtkScrolledWindow* _tmp8_ = NULL;
	GtkTextView* view = NULL;
	GtkTextView* _tmp9_ = NULL;
	GtkScrolledWindow* _tmp10_ = NULL;
	GtkTextView* _tmp11_ = NULL;
	GtkTextView* _tmp12_ = NULL;
	GtkSpellChecker* spell = NULL;
	GtkSpellChecker* _tmp13_ = NULL;
	GtkSpellChecker* _tmp14_ = NULL;
	GtkTextView* _tmp15_ = NULL;
	GtkBox* _tmp22_ = NULL;
	GError * _inner_error_ = NULL;
	parent_class = G_OBJECT_CLASS (window_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_WINDOW, Window);
	gtk_window_set_default_size ((GtkWindow*) self, 400, 300);
	gtk_window_set_title ((GtkWindow*) self, "Simple GtkSpell Demonstration");
	_tmp0_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 5);
	g_object_ref_sink (_tmp0_);
	box = _tmp0_;
	_tmp1_ = box;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp1_);
	_tmp2_ = box;
	_tmp3_ = self->priv->label;
	gtk_box_pack_start (_tmp2_, (GtkWidget*) _tmp3_, FALSE, FALSE, (guint) 0);
	_tmp4_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp4_);
	scroll = _tmp4_;
	_tmp5_ = box;
	_tmp6_ = scroll;
	gtk_box_pack_start (_tmp5_, (GtkWidget*) _tmp6_, TRUE, TRUE, (guint) 0);
	_tmp7_ = scroll;
	gtk_scrolled_window_set_policy (_tmp7_, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
	_tmp8_ = scroll;
	gtk_scrolled_window_set_shadow_type (_tmp8_, GTK_SHADOW_IN);
	_tmp9_ = (GtkTextView*) gtk_text_view_new ();
	g_object_ref_sink (_tmp9_);
	view = _tmp9_;
	_tmp10_ = scroll;
	_tmp11_ = view;
	gtk_container_add ((GtkContainer*) _tmp10_, (GtkWidget*) _tmp11_);
	_tmp12_ = view;
	gtk_text_view_set_wrap_mode (_tmp12_, GTK_WRAP_WORD);
	_tmp13_ = gtk_spell_checker_new ();
	g_object_ref_sink (_tmp13_);
	spell = _tmp13_;
	_tmp14_ = spell;
	_tmp15_ = view;
	gtk_spell_checker_attach (_tmp14_, _tmp15_);
	{
		GtkLabel* _tmp16_ = NULL;
		_tmp16_ = self->priv->label;
		gtk_label_set_label (_tmp16_, "Type some text into the text box.\n" "Try misspelling some words.  Then right-click on them.");
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GtkLabel* _tmp17_ = NULL;
		GError* _tmp18_ = NULL;
		const gchar* _tmp19_ = NULL;
		gchar* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp17_ = self->priv->label;
		_tmp18_ = e;
		_tmp19_ = _tmp18_->message;
		_tmp20_ = g_strconcat ("GtkSpell was unable to initialize.\n", _tmp19_, NULL);
		_tmp21_ = _tmp20_;
		gtk_label_set_label (_tmp17_, _tmp21_);
		_g_free0 (_tmp21_);
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (spell);
		_g_object_unref0 (view);
		_g_object_unref0 (scroll);
		_g_object_unref0 (box);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
	}
	_tmp22_ = box;
	gtk_widget_show_all ((GtkWidget*) _tmp22_);
	_g_object_unref0 (spell);
	_g_object_unref0 (view);
	_g_object_unref0 (scroll);
	_g_object_unref0 (box);
	return obj;
}


static void window_class_init (WindowClass * klass) {
	window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (WindowPrivate));
	G_OBJECT_CLASS (klass)->constructor = window_constructor;
	G_OBJECT_CLASS (klass)->finalize = window_finalize;
}


static void window_instance_init (Window * self) {
	GtkLabel* _tmp0_ = NULL;
	self->priv = WINDOW_GET_PRIVATE (self);
	_tmp0_ = (GtkLabel*) gtk_label_new (NULL);
	g_object_ref_sink (_tmp0_);
	self->priv->label = _tmp0_;
}


static void window_finalize (GObject* obj) {
	Window * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_WINDOW, Window);
	_g_object_unref0 (self->priv->label);
	G_OBJECT_CLASS (window_parent_class)->finalize (obj);
}


GType window_get_type (void) {
	static volatile gsize window_type_id__volatile = 0;
	if (g_once_init_enter (&window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Window), 0, (GInstanceInitFunc) window_instance_init, NULL };
		GType window_type_id;
		window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "Window", &g_define_type_info, 0);
		g_once_init_leave (&window_type_id__volatile, window_type_id);
	}
	return window_type_id__volatile;
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	Window* win = NULL;
	Window* _tmp0_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = window_new ();
	g_object_ref_sink (_tmp0_);
	win = _tmp0_;
	gtk_widget_show ((GtkWidget*) win);
	g_signal_connect ((GtkWidget*) win, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	gtk_main ();
	result = 0;
	_g_object_unref0 (win);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return _vala_main (argv, argc);
}



